### ISSUE TITLE
Research about docker

### ISSUE THREAD

**Issue by heroahmadi** [ezabintangr/star-pos#11]
**Acceptance Criteria:**

1. Do research about docker
2. Create a documentation in google docs
3. The documentation must answer these following questions:
  a. What is docker?
  b. What is docker image?
  c. What is docker container?
  d. How to build a docker image?
  e. How to run a docker container?
  f. What is docker network? Mention and explain every docker network
  g. What is port forwarding?
  h. What is docker volume?
  i. What is docker compose?

**Comment by ezabintangr** [comment]
Here's the link for file : https://docs.google.com/document/d/19O2xmT0y7NQKa33eaJIco4CNqaWmlALhis2_ybeFkAU/edit?usp=sharing
