### ISSUE TITLE
Feature Assessment

### ISSUE THREAD

**Issue by heroahmadi** [ezabintangr/star-pos#4]
Acceptance Criteria
1. Create document that contains the features and the use cases of the application below:
  a. https://infypos.infyom.com/#/login
  b. https://dashboard.post.app/
2. Create ERD

Document template: https://docs.google.com/spreadsheets/d/1RxQar-8aSFRp54cFmbY5rIFZCQBrKYMINtRp8T2JaW0/edit?usp=sharing

**Comment by ezabintangr** [comment]
1. Document of feature list: https://docs.google.com/spreadsheets/d/16tGE9imcCO_M-jHgTZDDUM1CG7OICFE6/edit?usp=sharing&ouid=102041631596290173229&rtpof=true&sd=true

2. ERD: https://drive.google.com/file/d/1FxyIqFm2gBgpN0ZMqZE1wm9omQ1_Jn4G/view?usp=sharing

**Comment by heroahmadi** [comment]
> 1. Document of feature list: https://docs.google.com/spreadsheets/d/16tGE9imcCO_M-jHgTZDDUM1CG7OICFE6/edit?usp=sharing&ouid=102041631596290173229&rtpof=true&sd=true
> 2. ERD: https://drive.google.com/file/d/1FxyIqFm2gBgpN0ZMqZE1wm9omQ1_Jn4G/view?usp=sharing

Reviews:

- Add `role varchar(25)` in User
- Make sure all tables have created and updated at
- Add table transactions_detail that will store transaction snapshot. Each row will contain transactions id, product name, and price for each bought product
- Cart and product need many to many relationship
- Why user have relationship with category?
- Please add datatype for each column

**Comment by ezabintangr** [comment]
Here's ERD improvement: https://drive.google.com/file/d/1CVMb_QZFlVSmxJkuGMY1VVjp1wcebWGJ/view?usp=sharing

**Comment by heroahmadi** [comment]
- Remove price_per_unit column in cart_product. Because for cart, we should get price from product table directly
- category name datatype is varchar

Other than that looks good to me. After fixing this please move this issue to done and work on the next issue

**Comment by ezabintangr** [comment]
Here's ERD final: https://drive.google.com/file/d/1kmb30DabgxGbN5HDF9MVk91jZzU9gGFi/view?usp=sharing

**Comment by ezabintangr** [comment]
Here's some improvement of ERD final: https://drive.google.com/file/d/1PLCxsoEmCVBoIyteZAeglnkXfE6EuBSH/view?usp=sharing

**Comment by heroahmadi** [comment]
@ezabintangr please update ERD based on our discussion. (product, category, cart, outlet, discount, does not need relation to user)
